### ISSUE TITLE
Getting error while integrate with angular 5

### ISSUE THREAD

**Issue by vikas-cis-zz** [j-zeng/angular2-http-file-upload#12]
ERROR in ./node_modules/angular2-http-file-upload/uploader/upload-item.ts
Module build failed: Error: /windows/work/harsh/asd-instrument-website/node_modules/angular2-http-file-upload/uploader/upload-item.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (/windows/work/harsh/asd-instrument-website/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:648:23)
    at plugin.done.then (/windows/work/harsh/asd-instrument-website/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./node_modules/angular2-http-file-upload/index.js 2:20-53
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
ERROR in ./node_modules/angular2-http-file-upload/uploader/uploader.ts
Module build failed: Error: /windows/work/harsh/asd-instrument-website/node_modules/angular2-http-file-upload/uploader/uploader.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (/windows/work/harsh/asd-instrument-website/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:648:23)
    at plugin.done.then (/windows/work/harsh/asd-instrument-website/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./node_modules/angular2-http-file-upload/index.js 4:17-47
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by koneru9999** [comment]
You may use this https://www.npmjs.com/package/angular-http-file-upload . 

The above is a retrofit version of angular2-http-file-upload for angular 5.
